service:
  name: halfway-serverless-api
# app and org for use with dashboard.serverless.com
# This serverless app link might be breaking github deploy action
# app: halfway-serverless-api
# org: darindev1000

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  customDomain:
    domainName: v1.halfway.api.darindev1000.com
    certificateName: "v1.halfway.api.darindev1000.com"
    basePath: "${self:provider.stage}"
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: edge
    enabled: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
provider:
  name: aws
  runtime: nodejs12.x
  # profile: darindev1000
  region: us-east-1
  stage: dev
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
