service:
  name: halfway-serverless-api
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: prod
  profile: default

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
